//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Monitoring_APIs_MultiplayerAPI_howplay {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Monitoring_APIs_MultiplayerAPI_howplay() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitoring.APIs.MultiplayerAPI.howplay", typeof(Monitoring_APIs_MultiplayerAPI_howplay).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Чтобы играть с другими пользователями по сети Voxel в игру Minecraft: Bedrock Edition, вам необходимо иметь саму игру и клиент Voxel. Зайдите в выбор издания, нажмите кнопку &quot;Minecraft: Bedrock Edition&quot;. Далее необходимо зайти в игру на любой версии и в разделе &quot;Друзья&quot;, где игры по локальной сети, будут отображены все локальные миры пользователей Voxel, подключенных к сети GameLynx. Если у вас нет миров, убедитесь, что вы подключены к глобальной сети. А может, просто никто сейчас не играет..
    /// </summary>
    internal static string label3_Text {
        get {
            return ResourceManager.GetString("label3.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Чтобы хостить мир в сеть Voxel, необходимо и иметь клиент Voxel и игру. Зайдите в выбор издания, нажмите кнопку &quot;Minecraft: Bedrock Edition&quot;. Далее просто заходите в игру и в ваш мир. Теперь в разделе &quot;Друзья&quot; все пользователи Voxel могут увидеть ваш мир..
    /// </summary>
    internal static string label6_Text {
        get {
            return ResourceManager.GetString("label6.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Чтобы хостить мир в сеть Voxel, необходимо и иметь клиент Voxel и игру. Далее просто заходите в игру и в ваш мир, нажимаете на клавишу &quot;ESC&quot;, и нажимаете кнопку &quot;Открыть мир для сети&quot;, далее &quot;Открыть мир для сети&quot;. Далее заходите в Voxel Multiplayer, и в выборе издания Minecraft выбираете Minecraft: Java Edition, Нажимаете на &quot;+&quot;, программа обнаружит ваш мир и добавит его в список для пользователей Voxel..
    /// </summary>
    internal static string label7_Text {
        get {
            return ResourceManager.GetString("label7.Text", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Ищет локализованную строку, похожую на Чтобы играть с другими пользователями по сети Voxel в игру Minecraft: Java Edition, вам необходимо иметь саму игру и клиент Voxel. Далее необходимо зайти в меню GameLynx раздела Minecraft, далее нажать кнопку &quot;Minecraft: Java Edition&quot;, будут отображены все локальные миры пользователей Voxel, которые выложили свой локальный мир. Чтобы зайти, нажмите на кнопку &quot;Играть&quot; выбраного вами мира, зайдите на ту же версию что и мир, в меню нажмите кнопку &quot;Сетевая игра&quot; и снизу в локальных мирах будет отображен выбранн [остаток строки не уместился]&quot;;.
    /// </summary>
    internal static string label9_Text {
        get {
            return ResourceManager.GetString("label9.Text", resourceCulture);
        }
    }
}
