//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
/// </summary>
// Этот класс создан автоматически классом StronglyTypedResourceBuilder
// с помощью такого средства, как ResGen или Visual Studio.
// Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
// с параметром /str или перестройте свой проект VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Voxel_Properties_Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Voxel_Properties_Resources() {
    }
    
    /// <summary>
    ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Voxel.Properties.Resources", typeof(Voxel_Properties_Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
    ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _150px_AV {
        get {
            object obj = ResourceManager.GetObject("150px_AV", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _50px_DS {
        get {
            object obj = ResourceManager.GetObject("_50px_DS", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _50px_SITE {
        get {
            object obj = ResourceManager.GetObject("_50px_SITE", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _50px_TG {
        get {
            object obj = ResourceManager.GetObject("_50px_TG", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap _50px_YT {
        get {
            object obj = ResourceManager.GetObject("_50px_YT", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap bad_ping {
        get {
            object obj = ResourceManager.GetObject("bad_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap cloud {
        get {
            object obj = ResourceManager.GetObject("cloud", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap exit {
        get {
            object obj = ResourceManager.GetObject("exit", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap gamelynx {
        get {
            object obj = ResourceManager.GetObject("gamelynx", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap low_ping {
        get {
            object obj = ResourceManager.GetObject("low_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap mcJava {
        get {
            object obj = ResourceManager.GetObject("mcJava", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap mcJava_dark {
        get {
            object obj = ResourceManager.GetObject("mcJava_dark", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap minecraft {
        get {
            object obj = ResourceManager.GetObject("minecraft", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap minecraft_dark {
        get {
            object obj = ResourceManager.GetObject("minecraft_dark", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap norm_ping {
        get {
            object obj = ResourceManager.GetObject("norm_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ok_ping {
        get {
            object obj = ResourceManager.GetObject("ok_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap onlineGame {
        get {
            object obj = ResourceManager.GetObject("onlineGame", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap title {
        get {
            object obj = ResourceManager.GetObject("title", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ultra_bad_ping {
        get {
            object obj = ResourceManager.GetObject("ultra_bad_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap unknown_ping {
        get {
            object obj = ResourceManager.GetObject("unknown_ping", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
